/**
 * Measure and aggregate functions plus grouping keys (§11, §12).
 *
 * `validGrains` is semantically important because the denominator of `win_rate()` changes
 * with the analysis grain. Results must state that denominator explicitly (§22).
 */
import type { FunctionDef, GroupKeyDef } from './types.js';

export const FUNCTIONS: Record<string, FunctionDef> = {
  win_rate: {
    id: 'win_rate',
    labelKo: '승률',
    descriptionKo: '조건을 만족한 단위 중 승리한 비율입니다.',
    kind: 'aggregate',
    params: [],
    returns: 'rate',
    validGrains: ['team', 'player', 'event'],
    sqlTemplate: 'avg(CASE WHEN {win} THEN 1.0 ELSE 0.0 END)',
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 1,
  },
  loss_rate: {
    id: 'loss_rate',
    labelKo: '패배율',
    descriptionKo: '조건을 만족한 단위 중 패배한 비율입니다.',
    kind: 'aggregate',
    params: [],
    returns: 'rate',
    validGrains: ['team', 'player', 'event'],
    sqlTemplate: 'avg(CASE WHEN NOT {win} THEN 1.0 ELSE 0.0 END)',
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 2,
  },
  all_values: {
    id: 'all_values',
    labelKo: '선택한 값 모두',
    descriptionKo: '반복 사건에서 선택한 값이 각각 한 번 이상 나타났는지 확인합니다.',
    kind: 'scalar',
    params: [{ name: 'membership', labelKo: '목록 조건', type: 'bool' }],
    returns: 'bool',
    validGrains: ['match', 'team', 'player', 'event'],
    rank: 50,
  },
  opponent_has_champion: {
    id: 'opponent_has_champion',
    labelKo: '상대팀 챔피언 포함',
    descriptionKo: '상대팀 로스터에 지정한 챔피언 중 한 명 이상이 있는지 확인합니다.',
    kind: 'scalar',
    params: [
      { name: 'champion1', labelKo: '챔피언 1', type: 'string' },
      { name: 'champion2', labelKo: '챔피언 2', type: 'string', optional: true },
      { name: 'champion3', labelKo: '챔피언 3', type: 'string', optional: true },
      { name: 'champion4', labelKo: '챔피언 4', type: 'string', optional: true },
      { name: 'champion5', labelKo: '챔피언 5', type: 'string', optional: true },
    ],
    returns: 'bool',
    validGrains: ['team', 'player'],
    rank: 51,
  },
  ally_has_champion: {
    id: 'ally_has_champion',
    labelKo: '아군 챔피언 포함',
    descriptionKo:
      '선수 분석에서 기준 챔피언과 같은 팀의 다른 선수가 지정한 챔피언을 선택했는지 확인합니다. 같은 팀 챔피언 조합 승률에 사용합니다.',
    kind: 'scalar',
    params: [{ name: 'champion', labelKo: '챔피언', type: 'string' }],
    returns: 'bool',
    validGrains: ['player'],
    rank: 52,
  },
  opponent_has_champion_in_role: {
    id: 'opponent_has_champion_in_role',
    labelKo: '상대 포지션 챔피언',
    descriptionKo: '상대팀의 지정한 포지션 선수가 해당 챔피언을 선택했는지 확인합니다.',
    kind: 'scalar',
    params: [
      { name: 'champion', labelKo: '챔피언', type: 'string' },
      { name: 'role', labelKo: '포지션', type: 'string' },
    ],
    returns: 'bool',
    validGrains: ['player'],
    rank: 53,
  },
  purchased_item_by: {
    id: 'purchased_item_by',
    labelKo: '시점까지 아이템 구매',
    descriptionKo: '지정한 시점까지 선택한 아이템 중 하나를 구매했는지 확인합니다.',
    kind: 'scalar',
    params: [
      { name: 'at', labelKo: '판정 시점', type: 'time' },
      { name: 'item1', labelKo: '아이템 1', type: 'int' },
      ...Array.from({ length: 19 }, (_, index) => ({
        name: `item${index + 2}`,
        labelKo: `아이템 ${index + 2}`,
        type: 'int' as const,
        optional: true,
      })),
    ],
    returns: 'bool',
    validGrains: ['team', 'player'],
    rank: 54,
  },
  owns_item_at: {
    id: 'owns_item_at',
    labelKo: '시점 아이템 보유',
    descriptionKo: '구매·판매·파괴·구매 취소 기록을 반영해 지정한 시점의 보유 여부를 확인합니다.',
    kind: 'scalar',
    params: [
      { name: 'at', labelKo: '판정 시점', type: 'time' },
      { name: 'item1', labelKo: '아이템 1', type: 'int' },
      ...Array.from({ length: 19 }, (_, index) => ({
        name: `item${index + 2}`,
        labelKo: `아이템 ${index + 2}`,
        type: 'int' as const,
        optional: true,
      })),
    ],
    returns: 'bool',
    validGrains: ['team', 'player'],
    rank: 55,
  },
  count: {
    id: 'count',
    labelKo: '개수',
    descriptionKo: '조건을 만족한 단위의 수입니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'any', optional: true }],
    returns: 'int',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'count({0})',
    resultFormat: { unit: 'count', decimals: 0 },
    rank: 2,
  },
  rate: {
    id: 'rate',
    labelKo: '발생 비율',
    descriptionKo: '조건을 만족한 단위의 비율입니다.',
    kind: 'aggregate',
    params: [{ name: 'condition', labelKo: '조건', type: 'bool' }],
    returns: 'rate',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'avg(CASE WHEN {0} THEN 1.0 ELSE 0.0 END)',
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 3,
  },
  pick_rate: {
    id: 'pick_rate',
    labelKo: '픽률',
    descriptionKo: '분석 대상 경기 중 지정한 챔피언이 한 번 이상 선택된 경기의 비율입니다.',
    kind: 'aggregate',
    params: [{ name: 'champion', labelKo: '챔피언', type: 'string' }],
    returns: 'rate',
    validGrains: ['match'],
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 3,
  },
  ban_rate: {
    id: 'ban_rate',
    labelKo: '밴률',
    descriptionKo: '분석 대상 경기 중 지정한 챔피언이 한 번 이상 밴된 경기의 비율입니다.',
    kind: 'aggregate',
    params: [{ name: 'champion', labelKo: '챔피언', type: 'string' }],
    returns: 'rate',
    validGrains: ['match'],
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 4,
  },
  champion_win_rate: {
    id: 'champion_win_rate',
    labelKo: '챔피언 승률',
    descriptionKo: '지정한 챔피언을 선택한 선수의 승률입니다.',
    kind: 'aggregate',
    params: [{ name: 'champion', labelKo: '챔피언', type: 'string' }],
    returns: 'rate',
    validGrains: ['match'],
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 5,
  },
  champion_games: {
    id: 'champion_games',
    labelKo: '픽 경기 수',
    descriptionKo: '지정한 챔피언이 한 번 이상 선택된 경기 수입니다.',
    kind: 'aggregate',
    params: [{ name: 'champion', labelKo: '챔피언', type: 'string' }],
    returns: 'int',
    validGrains: ['match'],
    resultFormat: { unit: 'count', decimals: 0 },
    rank: 6,
  },
  role_pick_rate: {
    id: 'role_pick_rate',
    labelKo: '포지션 내 픽률',
    descriptionKo: '지정한 포지션의 전체 선택 슬롯 중 해당 챔피언이 선택된 비율입니다.',
    kind: 'aggregate',
    params: [
      { name: 'champion', labelKo: '챔피언', type: 'string' },
      { name: 'role', labelKo: '포지션', type: 'string' },
    ],
    returns: 'rate',
    validGrains: ['match'],
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 7,
  },
  success_rate: {
    id: 'success_rate',
    labelKo: '성공률',
    descriptionKo:
      '기준 사건이 일어난 횟수 대비, 정해진 시간 안에 다음 사건이 일어난 횟수의 비율입니다.',
    kind: 'aggregate',
    params: [],
    returns: 'rate',
    validGrains: ['event'],
    requiresClause: 'chain',
    sqlTemplate: 'avg(CASE WHEN {chain_hit} THEN 1.0 ELSE 0.0 END)',
    resultFormat: { unit: 'percent', decimals: 1 },
    rank: 8,
  },
  avg: {
    id: 'avg',
    labelKo: '평균',
    descriptionKo: '값의 산술 평균입니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'float' }],
    returns: 'same-as-arg',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'avg({0})',
    rank: 5,
  },
  median: {
    id: 'median',
    labelKo: '중앙값',
    descriptionKo: '값을 정렬했을 때 가운데 값입니다. 극단값에 덜 흔들립니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'float' }],
    returns: 'same-as-arg',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'median({0})',
    rank: 6,
  },
  sum: {
    id: 'sum',
    labelKo: '합계',
    descriptionKo: '값을 모두 더한 결과입니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'float' }],
    returns: 'same-as-arg',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'sum({0})',
    rank: 7,
  },
  min: {
    id: 'min',
    labelKo: '최솟값',
    descriptionKo: '값 중 가장 작은 것입니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'float' }],
    returns: 'same-as-arg',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'min({0})',
    rank: 8,
  },
  max: {
    id: 'max',
    labelKo: '최댓값',
    descriptionKo: '값 중 가장 큰 것입니다.',
    kind: 'aggregate',
    params: [{ name: 'value', labelKo: '값', type: 'float' }],
    returns: 'same-as-arg',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'max({0})',
    rank: 9,
  },
  duration: {
    id: 'duration',
    labelKo: '두 사건 사이의 시간',
    descriptionKo: '시작 사건부터 끝 사건까지 걸린 시간입니다.',
    kind: 'scalar',
    params: [
      { name: 'start', labelKo: '시작 사건', type: 'event' },
      { name: 'end', labelKo: '끝 사건', type: 'event' },
    ],
    returns: 'duration',
    validGrains: ['match', 'team', 'player'],
    resultFormat: { unit: 'seconds', decimals: 0 },
    rank: 10,
  },
  gold_diff: {
    id: 'gold_diff',
    labelKo: '골드 차이',
    descriptionKo: '지정한 시점에서 상대 팀과의 골드 차이입니다.',
    kind: 'frame-measure',
    params: [{ name: 'at', labelKo: '시점', type: 'time' }],
    returns: 'int',
    validGrains: ['team', 'player'],
    frameColumn: 'gold_diff',
    resultFormat: { unit: 'gold', decimals: 0 },
    rank: 11,
  },
  xp_diff: {
    id: 'xp_diff',
    labelKo: '경험치 차이',
    descriptionKo: '지정한 시점에서 상대 팀과의 경험치 차이입니다.',
    kind: 'frame-measure',
    params: [{ name: 'at', labelKo: '시점', type: 'time' }],
    returns: 'int',
    validGrains: ['team', 'player'],
    frameColumn: 'xp_diff',
    rank: 12,
  },
  kill_diff: {
    id: 'kill_diff',
    labelKo: '킬 차이',
    descriptionKo: '지정한 시점까지 누적된 킬 차이입니다.',
    kind: 'frame-measure',
    params: [{ name: 'at', labelKo: '시점', type: 'time' }],
    returns: 'int',
    validGrains: ['team'],
    frameColumn: 'kill_diff',
    rank: 13,
  },
  bucket: {
    id: 'bucket',
    labelKo: '구간',
    descriptionKo: '값을 일정한 크기의 구간으로 나눕니다.',
    kind: 'scalar',
    params: [
      { name: 'value', labelKo: '값', type: 'float' },
      { name: 'size', labelKo: '구간 크기', type: 'float' },
    ],
    returns: 'category',
    validGrains: ['match', 'team', 'player', 'event'],
    sqlTemplate: 'floor({0} / {1}) * {1}',
    rank: 14,
  },
};

export const GROUP_KEYS: Record<string, GroupKeyDef> = {
  champion: {
    id: 'champion',
    labelKo: '챔피언',
    descriptionKo: '선수가 선택한 챔피언별로 나눕니다.',
    type: 'champion',
    // Five champions per team would multiply rows; validation blocks this with E-SEM-051.
    validGrains: ['player'],
    sql: 'champion',
    minSample: 30,
    rank: 1,
  },
  role: {
    id: 'role',
    labelKo: '역할',
    descriptionKo: '탑·정글·미드·원딜·서포터로 나눕니다.',
    type: 'role',
    validGrains: ['player'],
    sql: 'role',
    minSample: 30,
    rank: 2,
  },
  side: {
    id: 'side',
    labelKo: '진영',
    descriptionKo: '블루·레드 진영으로 나눕니다.',
    type: 'team',
    validGrains: ['team', 'player'],
    sql: 'side',
    rank: 3,
  },
  patch: {
    id: 'patch',
    labelKo: '패치',
    descriptionKo: '게임 버전별로 나눕니다.',
    type: 'category',
    validGrains: ['match', 'team', 'player'],
    sql: 'patch',
    rank: 4,
  },
  position_region: {
    id: 'position_region',
    labelKo: '퍼스트 블러드 영역',
    descriptionKo: '퍼스트 블러드가 일어난 미니맵 영역별로 나눕니다.',
    type: 'region',
    validGrains: ['team'],
    sql: 'first_blood_region',
    minSample: 30,
    rank: 5,
  },
  duration_bucket: {
    id: 'duration_bucket',
    labelKo: '경기 길이 구간',
    descriptionKo: '경기 길이를 5분 구간으로 나눕니다.',
    type: 'category',
    validGrains: ['match', 'team', 'player'],
    sql: 'floor(duration_s / 300) * 5',
    rank: 6,
  },
};
