/**
 * Versioned DSL syntax and cross-layer capability manifest.
 *
 * `parser` means the syntax has a stable AST representation. `engine` means PlanBuilder can
 * execute the constrained form described here. `visualBuilder` describes whether cards can edit
 * it without falling back to an advanced fragment. AI generation is deliberately restricted to
 * executable constructs, even when the parser accepts a wider future-facing syntax.
 */
import type { DslLanguageSpec } from './types.js';

export const DSL_LANGUAGE: DslLanguageSpec = {
  version: '2026.09.9',
  ebnf: [
    'program = [ analyze_clause ] ( simple_statement | compare_statement ) ;',
    'analyze_clause = "ANALYZE" scope ;',
    'simple_statement = [ chain_clause ] [ when_clause ] [ group_clause ] return_clause ;',
    'compare_statement = "COMPARE" compare_arm ( "VS" compare_arm )+ [ group_clause ] return_clause ;',
    'compare_arm = "WHEN" expression [ "AS" identifier ] ;',
    'chain_clause = "AFTER" event_ref [ "WITHIN" duration ] [ "IF" expression ] ;',
    'when_clause = "WHEN" expression ;',
    'group_clause = "GROUP" "BY" group_item ( "," group_item )* ;',
    'group_item = expression [ "AS" identifier ] ;',
    'return_clause = "RETURN" return_item ( "," return_item )* ;',
    'return_item = expression [ "AS" identifier ] ;',
    'scope = "match" | "team" | "blue" | "red" | "team.blue" | "team.red" | "opponent" | "player" | "player(" string ")" ;',
    'expression = logical_or ;',
    'logical_or = logical_and ( "OR" logical_and )* ;',
    'logical_and = logical_not ( "AND" logical_not )* ;',
    'logical_not = [ "NOT" ] relational ;',
    'relational = additive [ comparison | membership | spatial | temporal ] ;',
    'comparison = ( "=" | "!=" | "<>" | ">" | ">=" | "<" | "<=" ) additive ;',
    'membership = [ "NOT" ] "IN" ( "(" expression ( "," expression )* ")" | expression ) ;',
    'spatial = "IN" region_ref | "WITHIN" number "OF" landmark | "NEAR" landmark ;',
    'temporal = ( "BEFORE" | "AFTER" ) event_ref [ "WITHIN" duration ] | "WITHIN" duration [ ( "BEFORE" | "AFTER" ) event_ref ] | "BETWEEN" additive "AND" additive | "AT" additive | ( "DURING" | "UNTIL" ) additive ;',
    'additive = multiplicative ( ( "+" | "-" ) multiplicative )* ;',
    'multiplicative = unary ( ( "*" | "/" | "%" ) unary )* ;',
    'unary = [ "-" ] postfix ;',
    'postfix = primary ( "." identifier | "(" [ expression ( "," expression )* ] ")" | "[" occurrence "]" )* ;',
    'primary = number | percent | duration | clock | string | boolean | "null" | identifier | "(" expression ")" ;',
    'region_ref = "region(" string ")" ;',
    'event_ref = [ event_scope "." ] event_surface [ "[" occurrence "]" ] ;',
    'occurrence = positive_integer | "first" | "last" ;',
    'event_scope = "team" | "blue" | "red" | "opponent" ;',
    'landmark = identifier "." identifier ;',
    'identifier = ASCII letter or underscore followed by ASCII letters, digits, or underscores ;',
    'number = unsigned integer or decimal ;',
    'percent = number "%" ;',
    'string = double-quoted text with backslash escapes for n, r, t, double quote, and backslash ;',
    'boolean = "true" | "false" ;',
    'duration = attached duration parts such as 90s, 1m30s, or 1h2m3s ;',
    'clock = MM:SS or HH:MM:SS with two-digit non-leading fields below 60 ;',
    'trivia = whitespace | "--" line comment | "/*" block comment "*/" ;',
  ],
  precedence: [
    { level: 1, associativity: 'left', operators: ['OR'] },
    { level: 2, associativity: 'left', operators: ['AND'] },
    { level: 3, associativity: 'right', operators: ['NOT'] },
    {
      level: 4,
      associativity: 'none',
      operators: [
        '=',
        '!=',
        '<>',
        '>',
        '>=',
        '<',
        '<=',
        'IN',
        'NOT IN',
        'WITHIN',
        'NEAR',
        'BEFORE',
        'AFTER',
        'DURING',
        'UNTIL',
        'BETWEEN',
        'AT',
      ],
    },
    { level: 5, associativity: 'left', operators: ['+', '-'] },
    { level: 6, associativity: 'left', operators: ['*', '/', '%'] },
    { level: 7, associativity: 'right', operators: ['unary -'] },
    { level: 8, associativity: 'left', operators: ['.', '()'] },
  ],
  constructs: [
    {
      id: 'clauses',
      syntax: ['ANALYZE', 'AFTER ... WITHIN ... IF ...', 'WHEN', 'GROUP BY', 'RETURN'],
      parser: true,
      engine: true,
      visualBuilder: 'full',
      aiGenerate: true,
      constraints: [
        'Clause order is ANALYZE, AFTER, WHEN, GROUP BY, RETURN.',
        'RETURN is mandatory. ANALYZE, AFTER, WHEN, and GROUP BY are optional.',
        'A chain IF condition must be an event or a filter on that same event; success_rate() requires a chain.',
        'success_rate() keeps all trigger events in its denominator. Other measures keep only successful follow-ups.',
      ],
    },
    {
      id: 'compare',
      syntax: ['COMPARE WHEN condition [AS label] VS WHEN condition [AS label]', 'VS ...'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'At least two arms are required.',
        'Multiple RETURN measures are evaluated for every comparison arm.',
        'COMPARE and GROUP BY cannot be combined by the current engine.',
      ],
    },
    {
      id: 'team_scopes',
      syntax: ['team.event', 'blue.event', 'red.event', 'opponent.event'],
      parser: true,
      engine: true,
      visualBuilder: 'full',
      aiGenerate: true,
      constraints: [
        'team.event means either team.',
        'opponent.event is valid only for the IF event of a chain and is relative to its trigger.',
        'An unscoped team event inherits the ANALYZE team side when one exists.',
      ],
    },
    {
      id: 'player_scope',
      syntax: ['ANALYZE player', 'ANALYZE player("selector")'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['Player attributes and measures must be valid at player grain.'],
    },
    {
      id: 'boolean_logic',
      syntax: ['NOT condition', 'condition AND condition', 'condition OR condition'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['Use parentheses whenever AND and OR are mixed.'],
    },
    {
      id: 'opponent_roster',
      syntax: [
        'opponent_has_champion("Aatrox", "Vladimir")',
        'opponent_has_champion_in_role("LeBlanc", "MID")',
        'ally_has_champion("Rakan")',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Opponent presence works at team or player grain; ally and role matchup conditions use player grain.',
        'Returns true when at least one opposing-team participant selected one of the supplied champion names.',
        'Use exact dataset champion names supplied in the capability manifest.',
      ],
    },
    {
      id: 'point_in_time_items',
      syntax: [
        'purchased_item_by(15:00, 3165, 6609)',
        'owns_item_at(15:00, 3165, 6609)',
        'NOT owns_item_at(15:00, 3165, 6609)',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Use only at team or player grain.',
        'The first argument is a game clock and the remaining arguments are 1 to 20 item IDs.',
        'purchased_item_by checks whether any selected item was purchased by the cutoff.',
        'owns_item_at reconstructs inventory from purchases, sales, destruction, and undo events.',
        'An unscoped call targets the analyzed team or player; opponent. targets the opposing team.',
        'Matches shorter than the requested landmark are excluded before conditions are evaluated.',
      ],
    },
    {
      id: 'comparisons',
      syntax: ['=', '!=', '<>', '>', '>=', '<', '<='],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Comparison operators are non-associative; write a < b AND b < c, never a < b < c.',
        'The left side must be an executable frame measure, event field, or subject attribute.',
        '<> is parsed as != and canonical output uses !=.',
      ],
    },
    {
      id: 'event_occurrence',
      syntax: [
        'event[n]',
        'scope.event[n]',
        'event[first]',
        'event[last]',
        'scope.event[first]',
        'scope.event[last]',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'full',
      aiGenerate: true,
      constraints: [
        'n is an integer from 1 through 255 and counts matching events in timestamp and event-ID order.',
        'first selects the first matching event and last selects the final matching event.',
        'A field comparison on event[n] reads that same selected event row.',
      ],
    },
    {
      id: 'event_fields',
      syntax: ['event.field', 'scoped_event.field'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Use only fields listed in that event context.',
        'A repeatable event used as a scalar value requires a first_ or last_ event alias.',
      ],
    },
    {
      id: 'region_containment',
      syntax: ['event.position IN region("id")'],
      parser: true,
      engine: true,
      visualBuilder: 'full',
      aiGenerate: true,
      constraints: ['Use an exact supplied region ID and an event that exposes position.'],
    },
    {
      id: 'radius_distance',
      syntax: ['event.position WITHIN number OF landmark'],
      parser: true,
      engine: true,
      visualBuilder: 'none',
      aiGenerate: true,
      constraints: [
        'Distance is in raw game units.',
        'The target must be an exact supplied landmark ID.',
      ],
    },
    {
      id: 'event_temporal_gap',
      syntax: [
        'event AFTER event',
        'event AFTER event WITHIN duration',
        'event BEFORE event',
        'event BEFORE event WITHIN duration',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['Both operands must resolve to events.'],
    },
    {
      id: 'event_time_predicates',
      syntax: [
        'event WITHIN duration',
        'event AT clock',
        'event.time BETWEEN duration AND duration',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['The event must expose time.'],
    },
    {
      id: 'frame_measures',
      syntax: ['scope.gold_diff(clock)', 'scope.xp_diff(clock)', 'scope.kill_diff(clock)'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['Use only the grains and signatures supplied for each function.'],
    },
    {
      id: 'aggregates',
      syntax: [
        'win_rate()',
        'loss_rate()',
        'count([value])',
        'rate(condition)',
        'pick_rate("Ahri")',
        'ban_rate("Ahri")',
        'champion_win_rate("Ahri")',
        'champion_games("Ahri")',
        'role_pick_rate("Ahri", "MID")',
        'success_rate()',
        'avg(value)',
        'median(value)',
        'sum(value)',
        'min(value)',
        'max(value)',
        'duration(start_event, end_event)',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'RETURN expressions must be aggregate functions.',
        'duration() is a scalar value and must be nested in an aggregate such as avg().',
        'pick_rate() is match-grain only and counts distinct matches where the named champion appears.',
        'Champion overview measures are match-grain only so their sample is reported in matches.',
        'Function signatures and valid grains in the catalog are authoritative.',
      ],
    },
    {
      id: 'grouping',
      syntax: [
        'GROUP BY group_key [AS alias]',
        'GROUP BY bucket(event.time, duration)',
        'GROUP BY numbered_event.context_field',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Use only supplied group keys valid for the analysis grain.',
        'bucket() currently accepts only an event time field and a positive size.',
        'An event context field used for grouping must select an unambiguous numbered occurrence.',
      ],
    },
    {
      id: 'literals',
      syntax: [
        '123',
        '12.5',
        '55%',
        '"text"',
        '90s',
        '1m30s',
        '1h2m3s',
        '10:00',
        '1:02:30',
        'true',
        'false',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'Duration parts have no whitespace.',
        'A percent literal is normalized to a decimal number.',
        'Use literals only where the receiving expression accepts their type.',
      ],
    },
    {
      id: 'aliases',
      syntax: [
        'COMPARE WHEN condition AS label',
        'GROUP BY expression AS alias',
        'RETURN expression AS alias',
      ],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: ['Aliases are unquoted identifiers.'],
    },
    {
      id: 'membership',
      syntax: ['value IN (value, ...)', 'value NOT IN (value, ...)'],
      parser: true,
      engine: true,
      visualBuilder: 'partial',
      aiGenerate: true,
      constraints: [
        'The left side must be an executable event field or subject attribute.',
        'The list must contain one or more literals compatible with the left side.',
        'Wrap an event-field membership in all_values(...) to require every listed value.',
      ],
    },
    {
      id: 'arithmetic',
      syntax: ['+', '-', '*', '/', '%', 'unary -'],
      parser: true,
      engine: false,
      visualBuilder: 'none',
      aiGenerate: false,
      constraints: ['Reserved for future execution support. Do not generate.'],
    },
    {
      id: 'near',
      syntax: ['event.position NEAR landmark'],
      parser: true,
      engine: false,
      visualBuilder: 'none',
      aiGenerate: false,
      constraints: ['NEAR has no executable distance definition. Do not generate.'],
    },
    {
      id: 'during_until',
      syntax: ['value DURING value', 'value UNTIL value'],
      parser: true,
      engine: false,
      visualBuilder: 'none',
      aiGenerate: false,
      constraints: ['Reserved for future execution support. Do not generate.'],
    },
    {
      id: 'null_literal',
      syntax: ['null'],
      parser: true,
      engine: false,
      visualBuilder: 'none',
      aiGenerate: false,
      constraints: ['NULL comparisons are not executable. Do not generate.'],
    },
    {
      id: 'comments',
      syntax: ['-- line comment', '/* block comment */'],
      parser: true,
      engine: true,
      visualBuilder: 'none',
      aiGenerate: false,
      constraints: ['Comments are discarded from the AST. AI-generated DSL must omit comments.'],
    },
  ],
  generationRules: [
    'Generate only constructs where aiGenerate is true.',
    'All generated DSL must parse, validate semantically, and execute without a future-only construct.',
    'Prefer constructs with visualBuilder full or partial support so the result remains editable as cards.',
    'Never infer an event field, function signature, grain, landmark, or region that is not supplied.',
  ],
};
