"""Cross-language conformance for canonical hashes generated by TypeScript."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from lod_api.canonical import canonical_hash, canonical_json, canonical_stringify, canonicalize

CASES_DIR = Path(__file__).resolve().parents[3] / "tests" / "conformance" / "cases"
CASES = sorted(p.name for p in CASES_DIR.iterdir() if p.is_dir()) if CASES_DIR.exists() else []


def _read(case: str, name: str) -> str:
    return (CASES_DIR / case / name).read_text(encoding="utf-8")


@pytest.mark.parametrize("case", CASES)
def test_hash_matches_typescript(case: str) -> None:
    expected = json.loads(_read(case, "expected.hash.json"))
    if expected["hash"] is None:
        pytest.skip("AST is absent")
    ast = json.loads(_read(case, "expected.ast.json"))

    actual_json = canonical_json(ast)
    assert actual_json == expected["canonicalJson"], (
        "Canonical serialization differs from TypeScript.\n"
        f"TS    : {expected['canonicalJson'][:300]}\n"
        f"Python: {actual_json[:300]}"
    )
    assert canonical_hash(ast) == expected["hash"]


def test_cases_exist() -> None:
    assert len(CASES) > 15, "No conformance cases; run `pnpm gen:conformance`."


class TestCanonicalRules:
    def test_r1_drops_span(self) -> None:
        assert canonicalize({"kind": "X", "span": [0, 3]}) == {"kind": "X"}

    def test_r2_drops_raw_by_default(self) -> None:
        assert canonicalize({"seconds": 90, "raw": "90s"}) == {"seconds": 90}
        assert canonicalize({"seconds": 90, "raw": "90s"}, drop_raw=False) == {
            "seconds": 90,
            "raw": "90s",
        }

    def test_r4_sorts_keys(self) -> None:
        assert canonical_stringify(canonicalize({"b": 1, "a": 2})) == '{"a":2,"b":1}'

    def test_r5_folds_integral_floats(self) -> None:
        # JavaScript serializes 1.0 as 1 while Python normally emits 1.0.
        assert canonical_stringify(canonicalize(1.0)) == "1"
        assert canonical_stringify(canonicalize(1500.0)) == "1500"
        assert canonical_stringify(canonicalize(1.5)) == "1.5"
        assert canonical_stringify(canonicalize(-0.0)) == "0"

    @pytest.mark.parametrize("value", [1e-7, -1e-7, 1e21, -1e21])
    def test_rejects_numbers_outside_the_cross_language_domain(self, value: float) -> None:
        with pytest.raises(ValueError, match="Canonical numbers must"):
            canonicalize(value)

    @pytest.mark.parametrize(
        ("value", "expected"),
        [(1e-6, "0.000001"), (-1e-6, "-0.000001"), (1e20, "100000000000000000000")],
    )
    def test_accepts_cross_language_boundary_numbers(self, value: float, expected: str) -> None:
        assert canonical_stringify(canonicalize(value)) == expected

    def test_rejects_oversized_integer_input(self) -> None:
        with pytest.raises(ValueError, match="Canonical integers must"):
            canonicalize(10**21)

    def test_r6_preserves_array_order(self) -> None:
        assert canonical_stringify(canonicalize([1, 2])) != canonical_stringify(
            canonicalize([2, 1])
        )

    def test_hash_sorts_commutative_boolean_operands_only(self) -> None:
        left = {
            "kind": "BinaryExpr",
            "op": "AND",
            "left": {"kind": "NumberLit", "value": 2},
            "right": {"kind": "NumberLit", "value": 1},
        }
        right = {
            "kind": "BinaryExpr",
            "op": "AND",
            "left": {"kind": "NumberLit", "value": 1},
            "right": {"kind": "NumberLit", "value": 2},
        }
        assert canonical_json(left) != canonical_json(right)
        assert canonical_hash(left) == canonical_hash(right)

    def test_string_escaping_matches_json_stringify(self) -> None:
        assert canonical_stringify('a"b') == '"a\\"b"'
        assert canonical_stringify("a\nb") == '"a\\nb"'
        # Preserve non-ASCII text, matching JSON.stringify.
        assert canonical_stringify("탑 라인") == '"탑 라인"'

    def test_booleans_are_not_integers(self) -> None:
        # In Python bool is an int subclass, so type-check order matters.
        assert canonical_stringify(canonicalize(True)) == "true"
        assert canonical_stringify(canonicalize(False)) == "false"
